version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"  # Mapeia a porta 8080 do container para a porta 8080 do host
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres  # URL do banco de dados
      SPRING_DATASOURCE_USERNAME: postgres # Usuário do banco
      SPRING_DATASOURCE_PASSWORD: Nahb@0106  # Senha do banco
    depends_on:
      - db  # O serviço "app" depende do serviço "db"
    networks:
      - desafio-network

  db:
    image: postgres:13.15  # Usando a imagem do PostgreSQL 13
    environment:
      POSTGRES_DB: postgres  # Nome do banco de dados a ser criado
      POSTGRES_USER: postgres  # Usuário do banco
      POSTGRES_PASSWORD: Nahb@0106  # Senha do banco
    ports:
      - "5432:5432"  # Mapeia a porta 5432 do container para a porta 5432 do host
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Volume para persistir os dados do PostgreSQL
    networks:
      - desafio-network

volumes:
  postgres-data:

networks:
  desafio-network:
    driver: bridge
