spring:
  application:
    name: desafio

  security:
    basic:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Nahb@0106
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

flyway:
  ignore-missing-migrations: true
  baseline-on-migrate: true
